
WEBSERVER_DIR=../webserver

WSDL=./calc.wsdl
SERVER=./calc.c
CLIENT=./client.c
#LIBS+=-L. -lyunWS -lcommon /usr/local/pgsql/lib/libpq.a -lm -lxml2

include $(WEBSERVER_DIR)/Makefile

show:
	echo $(SOAPH)
